DentistClinic/Controllers/AnalysisController.cs
using DentistClinic.Core.Models;
using DentistClinic.Core.ViewModels;
using DentistClinic.CustomeValidation;
using DentistClinic.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DentistClinic.Controllers
{
    [Authorize(Roles = "Doctor")]
    public class AnalysisController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AnalysisController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }

		public IActionResult Index()
		{
			List<AnalysisViewModel> vmodel = _unitOfWork.analysisRepository.GetAll().Select(x => new AnalysisViewModel
			{
				Id = x.Id,
				Name = x.Name,
				Type = x.Type,
				IsDeleted = x.IsDeleted
			}).ToList();

			return View(vmodel);
		}


		[AjaxOnly]
		[HttpGet]
		public IActionResult Create()
		{
			AnalysisViewModel viewModal = new AnalysisViewModel();

			return PartialView("_Form", viewModal);
		}

		[AjaxOnly]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(AnalysisViewModel model)
		{

			if (ModelState.IsValid)
			{
				Analysis analysis = new Analysis();

				analysis.Name = model.Name;
				analysis.Type = model.Type;

				_unitOfWork.analysisRepository.Create(analysis);

				model.Id = analysis.Id;
				return PartialView("_Analysis", model);
			}
			else
			{
				return BadRequest("something is wrong..!!");
			}

		}


		[AjaxOnly]
		[HttpGet]
		public IActionResult Update(int id)
		{
			Analysis analysis = _unitOfWork.analysisRepository.GetById(id);

			if (analysis != null)
			{
				AnalysisViewModel viewModal = new AnalysisViewModel
				{
					Id = analysis.Id,
					Name = analysis.Name,
					Type = analysis.Type,
					IsDeleted = analysis.IsDeleted,
				};

				return PartialView("_Form", viewModal);
			}
			else
			{
				return BadRequest("something is wrong..!!");
			}


		}

		[AjaxOnly]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Update(AnalysisViewModel model)
		{
			if (ModelState.IsValid)
			{
				Analysis analysis = _unitOfWork.analysisRepository.GetById((int)model.Id!);

				if (analysis != null)
				{

					analysis.Name = model.Name;
					analysis.Type = model.Type;

					_unitOfWork.analysisRepository.Update(analysis);
					model.IsDeleted = analysis.IsDeleted;
					return PartialView("_Analysis", model);
				}
				else
				{
					return BadRequest("something is wrong..!!");
				}

			}
			else
			{
				return BadRequest("something is wrong..!!");
			}



		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		[AjaxOnly]
		public IActionResult ToggleStatus(int id)
		{
			Analysis analysis = _unitOfWork.analysisRepository.GetById(id);

			if (analysis != null)
			{
				analysis.IsDeleted = !analysis.IsDeleted;
				_unitOfWork.analysisRepository.Update(analysis);

				AnalysisViewModel viewModel = new AnalysisViewModel();
				viewModel.Name = analysis.Name;
				viewModel.Type = analysis.Type;
				viewModel.IsDeleted = analysis.IsDeleted;

				return Ok(viewModel);
			}
			else
			{
				return NotFound();
			}
		}
	}
}

DentistClinic/Controllers/PrescriptionController.cs
using DentistClinic.Core.Models;
using DentistClinic.Core.ViewModels;
using DentistClinic.CustomeValidation;
using DentistClinic.Data.Context;
using DentistClinic.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DentistClinic.Controllers
{
    [Authorize(Roles = "Doctor")]
    public class PrescriptionController : Controller
	{
        private readonly IUnitOfWork _unitOfWork;
        private readonly ApplicationDbContext _applicationDbContext;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        //1)allowed extension
        public IEnumerable<string> AllowedExtensions { get; set; } = new List<string>() { ".jpg", ".png", ".jpeg" };
        //2)maxsize file
        public int MaxFileSize { get; set; } = 2097152;

        public PrescriptionController(IUnitOfWork unitOfWork, ApplicationDbContext applicationDbContext, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            this._unitOfWork = unitOfWork;
            this._applicationDbContext = applicationDbContext;
            this._userManager = userManager;
            this._signInManager = signInManager;
        }
        public IActionResult Index()
		{
			return View();
		}


        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {

            Prescription prescription = _unitOfWork.prescriptionRepository.GetById(id);

            if (_signInManager.IsSignedIn(User))
            {
                var applicationUser = await _userManager.GetUserAsync(User) ?? new ApplicationUser();
                if (await _userManager.IsInRoleAsync(applicationUser, "User") && applicationUser.PatientId != prescription.PatientId)
                {
                    return LocalRedirect("~/Identity/Account/AccessDenied");
                }
            }

            

            if (prescription != null)
            {

                ////Medicines
                //var medicines = _unitOfWork.medicineRepository.GetAll().ToList();
                //var analysis = _unitOfWork.analysisRepository.GetAll().ToList();
                //var xrays = _unitOfWork.xrayRepository.GetAll().ToList();

                PrescriptionViewModel vmodel = new PrescriptionViewModel()
                {
                    Id = prescription.Id,
                    Date = prescription.Date,
                    Notes = prescription.Notes,
                    patient = prescription.Patient!,
                    //   MedicinesSelect = new SelectList(medicines, "Id", "Name").ToList(),
                    //AnalysisSelect = new SelectList(analysis, "Id", "Name").ToList(),
                    //XraysSelect = new SelectList(xrays, "Id", "Name").ToList(),
                    MedicinePrescriptions = prescription.MedicinePrescriptions!.Select(x => new MedicinePrescriptionViewModel
                    {
                        Id = x.Id,
                        Dose = x.Dose,
                        Days = x.Days,
                        Hours = x.Hours,
                        Medicine = x.Medicine,
                        MedicineId = x.MedicineId

                    }).ToList() ?? new List<MedicinePrescriptionViewModel>(),

                    AnalysisPrescriptions = prescription.AnalysisPrescriptions!.Select(x => new AnalysisPrescriptionViewModel
                    {
                        Id = x.Id,
                        Comment = x.Comment,
                        Cause = x.Cause,
                        PrescriptionId = x.PrescriptionId,
                        AnalysisId = x.AnalysisId,
                        Analysis = x.Analysis,
                        AnalysisPrescriptionImage = x.AnalysisPrescriptionImages?.ToList() ?? new List<AnalysisPrescriptionImage>()

                    }).ToList() ?? new List<AnalysisPrescriptionViewModel>(),

                    XrayPrescriptions = prescription.XrayPrescriptions!.Select(x => new XrayPrescriptionViewModel
                    {
                        Id = x.Id,
                        Comment = x.Comment,
                        Cause = x.Cause,
                        PrescriptionId = x.PrescriptionId,
                        XrayId = x.XrayId,
                        Xray = x.Xray,
                        XrayPrescriptionImages = x.XrayPrescriptionImages?.ToList() ?? new List<XrayPrescriptionImage>()

                    }).ToList() ?? new List<XrayPrescriptionViewModel>(),

                };

                return View(vmodel);

            }
            else
            {
                return BadRequest("something is wrong..!!");
            }
        }


        [HttpPost]
		[ValidateAntiForgeryToken]
		[AjaxOnly]
        public IActionResult Create(int id)
        {

			Patient patient = _unitOfWork.patientRepository.GetById(id);

			if (patient != null)
			{

				var today = DateOnly.FromDateTime(DateTime.Now);
				bool isExisted = patient.Prescriptions.Any(x => x.Date == today);

				if (isExisted) //patient has prescription in current day
				{
					return BadRequest("patient has prescription in current day!!");
                }

                Prescription prescription = new Prescription()
                {
                    Date = DateOnly.FromDateTime(DateTime.Now),
                    PatientId = id,
                };


                _unitOfWork.prescriptionRepository.Create(prescription);

				PrescriptionViewModel vmodel = new PrescriptionViewModel()
				{
					Id = prescription.Id,
					Date = prescription.Date,
					Notes = prescription.Notes,
				};


				return PartialView("_Prescription", vmodel);


            }
			else
			{
				return BadRequest("something is wrong..!!");
			}

        }

        [AjaxOnly]
        public IActionResult Delete(int id)
        {

            Prescription prescription = _unitOfWork.prescriptionRepository.GetById(id);

            if (prescription != null)
            {
				_unitOfWork.prescriptionRepository.Delete(prescription);


                return Ok();


            }
            else
            {
                return BadRequest("something is wrong..!!");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateComment(PrescriptionViewModel model)
        {
            Prescription prescription = _unitOfWork.prescriptionRepository.GetById((int)model.Id!);
            prescription.Notes = model.Notes;
            _unitOfWork.prescriptionRepository.Update(prescription);
            return RedirectToAction("Details", "Patients", new {id = prescription.PatientId});
        }

        [AjaxOnly]
        [HttpGet]
        public IActionResult CreateMedicine(int id)
        {
            //Medicines
            var medicines = _unitOfWork.medicineRepository.GetAll().Where(x => !x.IsDeleted)
                .Select(x => new { Id = x.Id, Name =$"{x.Name} : {x.Type}"}).ToList();
            MedicinePrescriptionViewModel vmodel = new MedicinePrescriptionViewModel();
            vmodel.PrescriptionId = id;



            vmodel.MedicinesSelect = new SelectList(medicines, "Id", "Name").ToList();

            return PartialView("_MedicineForm" , vmodel);


        }

        [AjaxOnly]
        [HttpPost]
        public IActionResult CreateMedicine([FromForm]MedicinePrescriptione medicinePrescriptione)
        {
            if (ModelState.IsValid)
            {
                var exsistedMedicine = _unitOfWork.medicinePrescriptionRepository.GetAll().FirstOrDefault(x => x.PrescriptionId == medicinePrescriptione.PrescriptionId && x.MedicineId == medicinePrescriptione.MedicineId);
                if (exsistedMedicine == null)
                {
                    _unitOfWork.medicinePrescriptionRepository.Create(medicinePrescriptione);

                    var medicine = _unitOfWork.medicineRepository.GetById(medicinePrescriptione.MedicineId);

                    MedicinePrescriptionViewModel vmodel = new MedicinePrescriptionViewModel()
                    {
                        Id = medicinePrescriptione.Id,
                        Dose = medicinePrescriptione.Dose,
                        Days = medicinePrescriptione.Days,
                        Hours = medicinePrescriptione.Hours,
                        Medicine = medicine,
                        MedicineId = medicine.Id
                    };

                    return PartialView("_MedicinePrescriptionDetails", vmodel);
                }
                else
                {
                    return BadRequest("Prescription has this Medicine..!!");
                }
            }
            else
            {
                return BadRequest("something is wrong..!!");
            }
            
        }

        [AjaxOnly]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteMedicine(int id)
        {
            MedicinePrescriptione medicinePrescriptione = _unitOfWork.medicinePrescriptionRepository.GetById(id);
            if(medicinePrescriptione != null)
            {
                _unitOfWork.medicinePrescriptionRepository.Delete(medicinePrescriptione);
                return Ok();
            }
            else
            {
                return BadRequest("something is wrong..!!");
            }
        }


        [AjaxOnly]
        [HttpGet]
        public IActionResult CreateAnalysis(int id)
        {
            //Analysis
            var analysis = _unitOfWork.analysisRepository.GetAll().Where(x => !x.IsDeleted)
                .Select(x => new { Id = x.Id, Name = $"{x.Name} : {x.Type}" }).ToList();
            AnalysisPrescriptionViewModel vmodel = new AnalysisPrescriptionViewModel();
            vmodel.PrescriptionId = id;

DentistClinic/Controllers/ReservationsController.cs
using DentistClinic.Core.ViewModels;
using DentistClinic.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DentistClinic.Controllers
{
	[Authorize(Roles = "Doctor , Reception")]
	public class ReservationsController : Controller
	{
        private readonly IUnitOfWork _unitOfWork;

        public ReservationsController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }

		public IActionResult Index()
		{
            List<AppointmentViewModel> vmodel = _unitOfWork.appointmentRepository.GetAll().Where(x => x.Patient != null)
            .Select(x => new AppointmentViewModel
            {
                Id = x.Id,
                Start = x.Start,
                End = x.End,
                StartTime = x.StartTime,
                EndTime = x.EndTime,
                PatientId = (int)x.PatientId!,
                Patient = x.Patient!
            }).ToList();

			return View(vmodel);
		}
	}
}

DentistClinic/Controllers/XrayController.cs
using DentistClinic.Core.Models;
using DentistClinic.Core.ViewModels;
using DentistClinic.CustomeValidation;
using DentistClinic.Services.Interfaces;
using DentistClinic.Services.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace DentistClinic.Controllers
{
    [Authorize(Roles = "Doctor")]
    public class XrayController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public XrayController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<XraysViewModel> vmodel = _unitOfWork.xrayRepository.GetAll().Select(x => new XraysViewModel
            {
                Id = x.Id,
                Name = x.Name,
                Type = x.Type,
                IsDeleted = x.IsDeleted
            }).ToList();

			return View(vmodel);
        }

		[AjaxOnly]
		[HttpGet]
		public IActionResult Create()
		{
			XraysViewModel viewModal = new XraysViewModel();

			return PartialView("_Form", viewModal);
		}

        [AjaxOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(XraysViewModel model)
        {

            if (ModelState.IsValid)
            {
                Xray xray = new Xray();

                xray.Name = model.Name;
                xray.Type = model.Type;

                _unitOfWork.xrayRepository.Create(xray);

				model.Id = xray.Id;
                return PartialView("_Xray" , model);
            }
            else
            {
                return BadRequest("something is wrong..!!");
            }

        }


		[AjaxOnly]
		[HttpGet]
		public IActionResult Update(int id)
		{
            Xray xray = _unitOfWork.xrayRepository.GetById(id);

            if(xray != null)
            {
				XraysViewModel viewModal = new XraysViewModel
				{
					Id = xray.Id,
					Name = xray.Name,
					Type = xray.Type,
					IsDeleted = xray.IsDeleted,
				};

				return PartialView("_Form", viewModal);
			}
            else
            {
				return BadRequest("something is wrong..!!");
			}

			
		}

		[AjaxOnly]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Update(XraysViewModel model)
		{
			if (ModelState.IsValid)
			{
				Xray xray = _unitOfWork.xrayRepository.GetById((int)model.Id!);

				if (xray != null)
				{

					xray.Name = model.Name;
					xray.Type = model.Type;

					_unitOfWork.xrayRepository.Update(xray);
                    model.IsDeleted = xray.IsDeleted;
					return PartialView("_Xray", model);
				}
				else
				{
					return BadRequest("something is wrong..!!");
				}
				
			}
			else
			{
				return BadRequest("something is wrong..!!");
			}
			
			

		}
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AjaxOnly]
        public IActionResult ToggleStatus(int id)
        {
            Xray xray = _unitOfWork.xrayRepository.GetById(id);

            if (xray != null)
            {
                xray.IsDeleted = !xray.IsDeleted;
                _unitOfWork.xrayRepository.Update(xray);

                XraysViewModel viewModel = new XraysViewModel();
                viewModel.Name = xray.Name;
                viewModel.Type = xray.Type;
                viewModel.IsDeleted = xray.IsDeleted;

                return Ok(viewModel);
            }
            else
            {
                return NotFound();
            }
        }
    }
}

DentistClinic/Views/Shared/_AthuntecationLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.png">
    <title>@ViewData["Title"] - DentistClinic</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css">
    <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css">
    <link rel="stylesheet" href="~/lib/select2/css/select2.min.css">
    <link rel="stylesheet" href="~/lib/flatpickr/flatpickr.min.css">
    <link rel="stylesheet" href="~/css/themeStyle.css">

</head>
<body>
    @RenderBody()

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script src="~/lib/flatpickr/flatpickr.min.js"></script>
    <script src="~/js/themeJs.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>

DentistClinic/Views/Shared/_DatatableCardHeader.cshtml
<div class="card-title">
    <div class="d-flex align-items-center position-relative my-1">
        <span class="svg-icon svg-icon-1 position-absolute ms-4">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor"></rect>
                <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor"></path>
            </svg>
        </span>
        <input type="text" data-kt-filter="search" class="form-control form-control-solid w-250px ps-14" placeholder="Search..." />
    </div>
    <div id="kt_datatable_example_1_export" class="d-none"></div>
</div>

DentistClinic/Views/Shared/_HomeFooter.cshtml
<!-- Newsletter Start -->
<div class="container-fluid position-relative pt-5 wow fadeInUp" data-wow-delay="0.1s" style="z-index: 1;">
    <div class="container">
        @* <div class="bg-primary p-5">
        <form class="mx-auto" style="max-width: 600px;">
        <div class="input-group">
        <input type="text" class="form-control border-white p-3" placeholder="Your Email">
        <button class="btn btn-dark px-4">Sign Up</button>
        </div>
        </form>
        </div> *@
    </div>
</div>
<!-- Newsletter End -->
<!-- Footer Start -->
<div class="container-fluid bg-dark text-light py-5 wow fadeInUp" data-wow-delay="0.3s" style="margin-top: -75px;">
    <div class="container pt-5">
        <div class="row g-5 pt-4">
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Quick Links</h3>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-light mb-2" asp-action="Index" asp-controller="Home"><i class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                    <a class="text-light mb-2" asp-action="About" asp-controller="Home"><i class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                    <a class="text-light mb-2" asp-action="Services" asp-controller="Home"><i class="bi bi-arrow-right text-primary me-2"></i>Our Services</a>
                    <a class="text-light" asp-action="Create" asp-controller="Contacts"><i class="bi bi-arrow-right text-primary me-2"></i>Contact Us</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
            </div>
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Get In Touch</h3>
                <p class="mb-2"><i class="bi bi-geo-alt text-primary me-2"></i>32 Al-Sagha St., Sherief Basha, Beni-Seuf</p>
                <p class="mb-2"><i class="bi bi-envelope-open text-primary me-2"></i>bhnsdentalclinic@gmail.com</p>
                <p class="mb-0"><i class="bi bi-telephone text-primary me-2"></i>+012 345 67890</p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Follow Us</h3>
                <div class="d-flex">
                    <a class="btn btn-lg btn-primary btn-lg-square rounded me-2" href="#"><i class="fab fa-twitter fw-normal"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded me-2" href="#"><i class="fab fa-facebook-f fw-normal"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded me-2" href="#"><i class="fab fa-linkedin-in fw-normal"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded" href="#"><i class="fab fa-instagram fw-normal"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid text-light py-4" style="background: #051225;">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 text-center text-md-start">
                <p class="mb-md-0">&copy; <a class="text-white border-bottom" href="#">BHNS</a>. All Rights Reserved.</p>
            </div>

        </div>
    </div>
</div>
<!-- Footer End -->
<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square rounded back-to-top"><i class="bi bi-arrow-up"></i></a>

DentistClinic/Views/Shared/_Prescription.cshtml
@model PrescriptionViewModel;
@inject UserManager<ApplicationUser> userManger;

@{
    var applicationUser = await userManger.GetUserAsync(User) ?? new ApplicationUser();
}

<div class="col-12 col-md-3 animate__animated animate__bounceIn prescription-box">   
    <!--begin::Card-->
    <div class="card mb-6 mb-xl-9" style="box-shadow: rgba(60, 64, 67, 0.3) 0px 1px 2px 0px, rgba(60, 64, 67, 0.15) 0px 2px 6px 2px;">
        <!--begin::Card body-->
        <div class="card-body py-2 px-3">
            <!--begin::Header-->
            <div class="d-flex flex-stack justify-content-end align-item-center mb-3">
                <!--begin::Menu-->
                <div>
                    <button type="button" class="btn btn-sm btn-icon btn-color-light-dark btn-active-light-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
                        <i class="fa-solid fa-ellipsis-vertical"></i>
                    </button>
                    <!--begin::Menu 3-->
                    <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg-light-primary fw-semibold w-200px py-3" data-kt-menu="true">
                        <!--begin::Heading-->
                        <div class="menu-item px-3">
                            <div class="menu-content text-muted pb-2 px-3 fs-7 text-uppercase">
                                Prescription
                            </div>
                        </div>
                        <!--end::Heading-->
                        <!--begin::Menu item-->
                        <div class="menu-item px-3">
                            <a class="menu-link px-3" asp-controller="Prescription" asp-action="Details" asp-route-id="@Model.Id">
                                Details
                            </a>
                        </div>
                        <!--end::Menu item-->
                        @if (await userManger.IsInRoleAsync(applicationUser, "Doctor"))
                        {
                            <!--begin::Menu item-->
                            <div class="menu-item px-3">
                                <a href="javascript:;" class="menu-link px-3 js-delete-prescription" data-url="/Prescription/Delete/@Model.Id">
                                    Delete
                                </a>
                            </div>
                            <!--end::Menu item-->
                        }
                    </div>
                    <!--end::Menu 3-->
                </div>
                <!--end::Menu-->
            </div>
            <!--end::Header-->
            <!--begin::Stats-->
            <div class="document-image text-center">
                <a asp-action="Details" asp-controller="Prescription" asp-route-id="@Model.Id">
                    <img src="~/assets/images/prescription2.png" alt="prescription" width="100px" />
                </a>
                <!--end::Stat-->
            </div>
            <!--end::Stats-->
            <!--begin::Stats-->
            <div class="d-flex flex-column my-1">
                <!--begin::Stat-->
                <div class="border border-dashed border-gray-300 mb-2 rounded d-flex flex-column align-items-start justify-content-center pt-4 pb-2 px-3">
                    <div class="date text-center mx-auto">
                        <i class="fa-regular fa-calendar fw-semibold"></i>
                        <span class="mx-2 report-end-date fw-semibold">@Model.Date</span>
                    </div>
                </div>
                <!--end::Stat-->
            </div>
            <!--end::Stats-->
        </div>
        <!--end::Card body-->
    </div>
    <!--end::Card-->

</div>