DentistClinic/Controllers/PatientsController.cs
using DentistClinic.Core.Models;
using DentistClinic.Core.ViewModels;
using DentistClinic.CustomeValidation;
using DentistClinic.Data.Context;
using DentistClinic.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq.Dynamic.Core;
using System.Security.Claims;

namespace DentistClinic.Controllers
{
    [Authorize(Roles = "Doctor , Reception")]
    public class PatientsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ApplicationDbContext _applicationDbContext;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public PatientsController(UserManager<ApplicationUser> userManager, IUnitOfWork unitOfWork , ApplicationDbContext applicationDbContext , SignInManager<ApplicationUser> signInManager)
        {
            this._userManager = userManager;
            this._unitOfWork = unitOfWork;
            this._applicationDbContext = applicationDbContext;
            this._signInManager = signInManager;
        }

        public IActionResult Index()
        {
            List<PatientViewModel> vmodels = _unitOfWork.patientRepository.GetAll().Where(x => x.IsDeleted)
                .Select(x => new PatientViewModel
                {
                    Id = x.Id,
                    FullName = x.FullName,
                    PhoneNumber = x.PhoneNumber,
                    Gender = x.Gender,
                    BirthDate = x.BirthDate,
                    IsDeleted = x.IsDeleted,

                }).ToList();
            return View(vmodels);
        }

        [HttpGet]
        public IActionResult Create()
        {
            //create a new patient 
            PatientViewModel vModel = new PatientViewModel();
            return View(vModel);
        }

        [HttpPost]
        public IActionResult Create(PatientViewModel model)
        {
            if (ModelState.IsValid)
            {
                //create new patient
                Patient patient = new Patient();
                patient.FirstName = model.FirstName;
                patient.LastName = model.LastName;
                patient.FullName = model.FirstName + " " + model.LastName;
                patient.PhoneNumber = model.PhoneNumber;
                patient.Address = model.Address;
                patient.Gender = model.Gender;
                patient.BirthDate = model.BirthDate;
                patient.Occupation = model.Occupation;

                _unitOfWork.patientRepository.Create(patient);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
           
          
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            if(_signInManager.IsSignedIn(User))
            {
                var applicationUser = await _userManager.GetUserAsync(User) ?? new ApplicationUser();
                if (await _userManager.IsInRoleAsync(applicationUser, "User") && applicationUser.PatientId != id)
                {
                    return LocalRedirect("~/Identity/Account/AccessDenied");
                }
            }


            //get patient 
            Patient model = _unitOfWork.patientRepository.GetById(id);
            PatientViewModel vmodel = new PatientViewModel()
            {
                Id = model.Id,
                FirstName = model.FirstName,
                LastName = model.LastName,
                FullName = model.FullName,
                PhoneNumber = model.PhoneNumber,
                Address = model.Address,
                Gender = model.Gender,
                BirthDate = model.BirthDate,
                Occupation = model.Occupation,
                ProfilePicture = model.ProfilePicture,
                ChiefComplainPatients = model.ChiefComplainPatients,
                Tplans = model.Tplans.Select(x => new TreatmentPlansViewModel
                {
                    Id = x.Id,
                    Name = x.Name,
                    StartDate = x.StartDate,
                    EndDate = x.EndDate,
                    Notes = x.Notes,
                    PatientId = x.PatientId,
                    Teeth = x.Teeth.Select(x => x.Name).ToList(),
                }).ToList(),
                Appointments = model.Appointments.Select(x => new AppointmentViewModel
                {
                    Id = x.Id,
                    Start = x.Start,
                    End = x.End,
                    StartTime = x.StartTime,
                    EndTime = x.EndTime,
                    PatientId = (int)x.PatientId!
                }).ToList(),
                PaymentRecords = model.PaymentRecords.Select(x => new PaymentViewModel
                {
                    Id = x.Id,
                    Date = x.Date,
                    Type = x.Type,
                    Value = x.Value,
                    Note = x.Note,
                    PatientId = x.Id

                }).ToList(),
                MedicalHistories = model.MedicalHistories.Select(x => new MedicalReportViewModel
                {
                    Id = x.Id,
                    Name = x.Name,
                    StartDate = x.StartDate,
                    EndDate = x.EndDate,
                    Notes = x.Notes,
                    Documentations = x.MedicalHistoryImages.Select(x => x.Image).ToList(),
                    PatientId = x.PatientId
                }).ToList(),
                Prescriptions = model.Prescriptions.Select(x => new PrescriptionViewModel
                {
                    Id = x.Id,
                    Date = x.Date,
                    Notes = x.Notes,
                    patient = x.Patient!,

                }).ToList(),
                CurentBalance = model.CurentBalance
            };

            List<PaymentRecord> payments = _unitOfWork.paymentsRepository.GetByPatientId(id);

            if(payments.Count() > 0)
            {
                double gainPayments = 0;
                foreach (var payment in payments)
                {
                    if(payment.Type == "Pay")
                    {
                        gainPayments += payment.Value;
                    }
                }

                gainPayments = gainPayments * -1;
                vmodel.GainPayment = gainPayments;
            }


            return View(vmodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AjaxOnly]
        public IActionResult ToggleStatus(int id)
        {
            Patient patient = _unitOfWork.patientRepository.GetById(id);

            if (patient != null)
            {
                patient.IsDeleted = !patient.IsDeleted;

                _unitOfWork.patientRepository.Update(patient);

                if (patient.IsDeleted)
                {
                    return Ok("Patient Has been Deleted");
                }
                else
                {
                    return Ok("Patient Has been Restored");
                }

               
            }
            else
            {
                return BadRequest("something is wrong..!!");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AjaxOnly]
        public async Task<IActionResult> Delete(int id)
        {
            Patient patient = _unitOfWork.patientRepository.GetById(id);
            ApplicationUser applicationUser = _userManager.Users.FirstOrDefault(x => x.PatientId == patient.Id)!;
            using var transaction = _applicationDbContext.Database.BeginTransaction();

            try
            {
                if (patient != null)
                {
                    _unitOfWork.patientRepository.Delete(patient);
                    if (applicationUser != null)
                    {
                        IdentityResult identityResult = await _userManager.DeleteAsync(applicationUser);
                        if (identityResult.Succeeded)
                        {
                            transaction.Commit();
                            return Ok();
                        }
                        else
                        {
                            return BadRequest("something is wrong..!!");
                        }
                    }
                    else
                    {
                        transaction.Commit();
                        return Ok();
                    }
                }
                else
                {
                    return BadRequest("something is wrong..!!");
                }


            }
            catch (Exception ex)
            {
                transaction.Rollback();
                return BadRequest(ex.Message);
            }
                        
        }

        [HttpPost]
        [AjaxOnly]
        public IActionResult GetPatients()
        {

            //--------------------------------------
            var start = int.Parse(Request.Form["start"]);
            var length = int.Parse(Request.Form["length"]);
            var orderColumnIndex = Request.Form["order[0][column]"];
            var orderColumnName = Request.Form[$"columns[{orderColumnIndex}][name]"];
            var orderColumnDir = Request.Form["order[0][dir]"];
            var searchValue = Request.Form["search[value]"];
            //---------------------------------------


            var patients = _unitOfWork.patientRepository.GetAll().Where(x => !x.IsDeleted).AsQueryable();

            if (!string.IsNullOrEmpty(searchValue))
                patients = patients.Where(x => x.FullName.Contains(searchValue) || x.PhoneNumber.Contains(searchValue));

            
            patients = patients.OrderBy($"{orderColumnName} {orderColumnDir}");

DentistClinic/Views/Patients/Create.cshtml
@model PatientViewModel;
@{
    ViewData["Title"] = "Create Patient";
}

<div class="card shadow-sm">
    <!--Begin Card::Header-->
    <div class="card-header">
        <h5 class="align-self-center m-0">Add Patient</h5>
    </div>
    <!--End Card::Header-->
    <!--Begin Card::Body-->
    <div class="card-body">
        <form id="PatientForm" method="post" asp-controller="Patients">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-6">
                    <div class="mb-3">
                        <div class="form-floating mb-2">
                            <input class="form-control form-control-solid" asp-for="FirstName" placeholder="FirstName..." />
                            <label class="form-label" asp-for="FirstName"></label>
                        </div>
                        <span class="text-danger d-block" asp-validation-for="FirstName"></span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="mb-3">
                        <div class="form-floating mb-2">
                            <input class="form-control form-control-solid" asp-for="LastName" placeholder="LastName..." />
                            <label class="form-label" asp-for="LastName"></label>
                        </div>
                        <span class="text-danger d-block" asp-validation-for="LastName"></span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="mb-3">
                        <div class="form-floating mb-2">
                            <input class="form-control form-control-solid" asp-for="PhoneNumber" placeholder="PhoneNumber..." />
                            <label class="form-label" asp-for="PhoneNumber"></label>
                        </div>
                        <span class="text-danger d-block" asp-validation-for="PhoneNumber"></span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="mb-3">
                        <div class="form-floating mb-2">
                            <input class="form-control form-control-solid patient-birthdate" asp-for="BirthDate" placeholder="BirthDate..." />
                            <label class="form-label" asp-for="BirthDate"></label>
                        </div>
                        <span class="text-danger d-block" asp-validation-for="BirthDate"></span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="mb-3">
                        <div class="form-floating mb-2">
                            <select class="form-select form-select-solid js-select2" data-control="select2" data-placeholder="Select Gender" data-hide-search="true" asp-for="Gender">
                                <option value="">Select Gender</option>
                                <option value="Male">Male</option>
                                <option value="Female">Female</option>
                                <option value="Child">Child</option>
                            </select>
                            <label class="form-label" asp-for="Gender"></label>
                        </div>
                        <span class="text-danger d-block" asp-validation-for="Gender"></span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="mb-3">
                        <div class="form-floating mb-2">
                            <input class="form-control form-control-solid" asp-for="Address" placeholder="Address..." />
                            <label class="form-label" asp-for="Address"></label>
                        </div>
                        <span class="text-danger d-block" asp-validation-for="Address"></span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="mb-3">
                        <div class="form-floating mb-2">
                            <input class="form-control form-control-solid" asp-for="Occupation" placeholder="Occupation..." />
                            <label class="form-label" asp-for="Occupation"></label>
                        </div>
                        <span class="text-danger d-block" asp-validation-for="Occupation"></span>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <!--End Card::Body-->
    <!--Begin Card::Footer-->
    <div class="card-footer py-2">
        <button type="submit" class="btn-sm btn btn-primary me-2" form="PatientForm">
            <span class="indicator-label">
                Save
            </span>
            <span class="indicator-progress">
                Please wait... <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
            </span>
        </button>
        <a class="btn btn-lignt text-primary" asp-action="Index">Cancel</a>
    </div>
    <!--End Card::Footer-->
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/patient.js"></script>
}

DentistClinic/Views/Patients/_Patient.cshtml
@model PatientViewModel;
<tr>
    <td class="d-none"></td>
    <td class="d-flex align-items-center">
        <!--begin:: Patient -->
        <div class="symbol  symbol-50px overflow-hidden me-3">
            <a href="/Patients/Details/@Model.Id">
                <div class="symbol-label">
                    @if (!String.IsNullOrEmpty(Model.ProfilePicture?.ToString()))
                    {
                        <img src="data:image /*;base64,@(Convert.ToBase64String(Model?.ProfilePicture!))" alt="Cover" class="w-100">
                    }
                    else
                    {
                        <img src="~/assets/images/user.jpg" alt="Cover" class="w-100">
                    }
                </div>
            </a>
        </div>
        <!--end::Patient-->
        <!--begin::Patient details-->
        <div class="d-flex flex-column">
            <a href="/Patients/Details/@Model?.Id" class="text-gray-800 text-hover-primary fw-bolder mb-1">@Model?.FullName</a>
            <span>@Model?.PhoneNumber</span>
        </div>
        <!--begin::Patient details-->
    </td>
    <td>@Model?.Gender</td>
    <td> @Model?.BirthDate.ToString("MMMM dd, yyyy")</td>
    <td>
        <span class="js-status badge badge-light-@(Model!.IsDeleted ? "danger" : "success") me-auto">
            @(Model!.IsDeleted ? "Deleted" : "Available")
        </span>
    </td>
    <td class="text-center">
        <a href="#" class="btn btn-light btn-active-light-primary btn-flex btn-center btn-sm" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
            Actions
            <!--begin::Svg Icon | path: /var/www/preview.keenthemes.com/keenthemes/metronic/docs/core/html/src/media/icons/duotune/arrows/arr072.svg-->
            <span class="svg-icon svg-icon-muted svg-icon-5">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z" fill="currentColor" />
                </svg>
            </span>
            <!--end::Svg Icon-->
        </a>
        <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 py-4" data-kt-menu="true" style="width:200px">
            <!--begin::Menu item-->
            <div class="menu-item px-3">
                <a href="javascript:;" class="menu-link px-3 js-toggle-status-patient" data-url="/Patients/ToggleStatus/@Model.Id">
                    Make it Available
                </a>
            </div>
            <!--end::Menu item-->
            <!--begin::Menu item-->
            <div class="menu-item px-3">
                <a asp-action="Delete" asp-controller="Patients" asp-route-id="@Model.Id" class="menu-link px-3">
                    Delete Permanently
                </a>
            </div>
            <!--end::Menu item-->
        </div>
    </td>
</tr>