DentistClinic/Controllers/MedicinesController.cs
using DentistClinic.Core.Models;
using DentistClinic.Core.ViewModels;
using DentistClinic.CustomeValidation;
using DentistClinic.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DentistClinic.Controllers
{
    [Authorize(Roles = "Doctor")]
    public class MedicinesController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;

		public MedicinesController(IUnitOfWork unitOfWork)
		{
			this._unitOfWork = unitOfWork;
		}
		public IActionResult Index()
		{
			List<MedicineViewModel> vmodel = _unitOfWork.medicineRepository.GetAll().Select(x => new MedicineViewModel
			{
				Id = x.Id,
				Name = x.Name,
				Type = x.Type,
				IsDeleted = x.IsDeleted
			}).ToList();

			return View(vmodel);
		}

		[AjaxOnly]
		[HttpGet]
		public IActionResult Create()
		{
			MedicineViewModel viewModal = new MedicineViewModel();

			return PartialView("_Form", viewModal);
		}

		[AjaxOnly]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(MedicineViewModel model)
		{

			if (ModelState.IsValid)
			{
				Medicine medicine = new Medicine();

				medicine.Name = model.Name;
				medicine.Type = model.Type;

				_unitOfWork.medicineRepository.Create(medicine);

				model.Id = medicine.Id;
				return PartialView("_Medicine", model);
			}
			else
			{
				return BadRequest("something is wrong..!!");
			}

		}


		[AjaxOnly]
		[HttpGet]
		public IActionResult Update(int id)
		{
			Medicine medicine = _unitOfWork.medicineRepository.GetById(id);

			if (medicine != null)
			{
				MedicineViewModel viewModal = new MedicineViewModel
				{
					Id = medicine.Id,
					Name = medicine.Name,
					Type = medicine.Type,
					IsDeleted = medicine.IsDeleted,
				};

				return PartialView("_Form", viewModal);
			}
			else
			{
				return BadRequest("something is wrong..!!");
			}


		}

		[AjaxOnly]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Update(MedicineViewModel model)
		{
			if (ModelState.IsValid)
			{
				Medicine medicine = _unitOfWork.medicineRepository.GetById((int)model.Id!);

				if (medicine != null)
				{

					medicine.Name = model.Name;
					medicine.Type = model.Type;

					_unitOfWork.medicineRepository.Update(medicine);
					model.IsDeleted = medicine.IsDeleted;
					return PartialView("_Medicine", model);
				}
				else
				{
					return BadRequest("something is wrong..!!");
				}

			}
			else
			{
				return BadRequest("something is wrong..!!");
			}



		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		[AjaxOnly]
		public IActionResult ToggleStatus(int id)
		{
			Medicine medicine = _unitOfWork.medicineRepository.GetById(id);

			if (medicine != null)
			{
				medicine.IsDeleted = !medicine.IsDeleted;
				_unitOfWork.medicineRepository.Update(medicine);

				MedicineViewModel viewModel = new MedicineViewModel();
				viewModel.Name = medicine.Name;
				viewModel.Type = medicine.Type;
				viewModel.IsDeleted = medicine.IsDeleted;

				return Ok(viewModel);
			}
			else
			{
				return NotFound();
			}
		}
	}
}

DentistClinic/Views/Medicines/Index.cshtml
@model IEnumerable<MedicineViewModel>
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery antiforgery;

@{
	ViewData["Title"] = "Index";
}

@section Styles {
	<link rel="stylesheet" href="~/assets/Plugins/datatables/datatables.bundle.css" />
}

<div class="bg-light-primary border border-primary border-3 border-dashed d-flex justify-content-between rounded w-100 p-5 mb-10">
	<div class="d-flex align-items-center">
		<div class="symbol symbol-40px me-4">
			<div class="symbol-label fs-2 fw-semibold">
				<!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
				<span class="svg-icon svg-icon-2 svg-icon-primary">
					<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" fill="none">
						<path d="M112 96c-26.5 0-48 21.5-48 48V256h96V144c0-26.5-21.5-48-48-48zM0 144C0 82.1 50.1 32 112 32s112 50.1 112 112V368c0 61.9-50.1 112-112 112S0 429.9 0 368V144zM554.9 399.4c-7.1 12.3-23.7 13.1-33.8 3.1L333.5 214.9c-10-10-9.3-26.7 3.1-33.8C360 167.7 387.1 160 416 160c88.4 0 160 71.6 160 160c0 28.9-7.7 56-21.1 79.4zm-59.5 59.5C472 472.3 444.9 480 416 480c-88.4 0-160-71.6-160-160c0-28.9 7.7-56 21.1-79.4c7.1-12.3 23.7-13.1 33.8-3.1L498.5 425.1c10 10 9.3 26.7-3.1 33.8z" fill="currentColor" />
					</svg>
				</span>
				<!--end::Svg Icon-->
			</div>
		</div>
		<!--begin::Content-->
		<div class="d-flex flex-column pe-0 pe-sm-10">
			<h5 class="mb-1">Medicines</h5>
		</div>
		<!--end::Content-->
	</div>
	<div>
		<a class="btn btn-sm btn-primary js-render-modal" href="javascript:;" data-url="/Medicines/Create" data-title="Add New Medicine">
			<i class="bi bi-plus-square-dotted"></i>
			Add
		</a>
	</div>
</div>
<div class="card shadow-sm">
	<!--Begin Card::Header-->
	<div class="card-header">
		<partial name="_DatatableCardHeader" />
		<div class="card-toolbar flex-row-fluid justify-content-end gap-5">
			<!--begin::Export dropdown-->
			<button type="button" class="btn btn-light-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
				<i class="ki-duotone ki-exit-down fs-2"><span class="path1"></span><span class="path2"></span></i>
				Export Report
			</button>
			<!--begin::Menu-->
			<div id="kt_datatable_example_export_menu" class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 w-200px py-4" data-kt-menu="true">
				<!--begin::Menu item-->
				<div class="menu-item px-3">
					<a href="#" class="menu-link px-3" data-kt-export="copy">
						Copy to clipboard
					</a>
				</div>
				<!--end::Menu item-->
				<!--begin::Menu item-->
				<div class="menu-item px-3">
					<a href="#" class="menu-link px-3" data-kt-export="excel">
						Export as Excel
					</a>
				</div>
				<!--end::Menu item-->
				<!--begin::Menu item-->
				<div class="menu-item px-3">
					<a href="#" class="menu-link px-3" data-kt-export="csv">
						Export as CSV
					</a>
				</div>
				<!--end::Menu item-->
				<!--begin::Menu item-->
				<div class="menu-item px-3">
					<a href="#" class="menu-link px-3" data-kt-export="pdf">
						Export as PDF
					</a>
				</div>
				<!--end::Menu item-->
			</div>
			<!--end::Menu-->
			<!--end::Export dropdown-->
			<!--begin::Hide default export buttons-->
			<div id="kt_datatable_example_buttons" class="d-none"></div>
		</div>
	</div>
	<!--End Card::Header-->
	<div class="card-body pt-0">
		<div class="table-responsive">
			<table id="kt_datatable_zero_configuration" class="js-datatables table table-row-dashed table-row-gray-300 gy-3 align-middle">
				<thead>
					<tr class="fw-bold fs-6 text-gray-800">
						<th>Name</th>
						<th>Type</th>
						<th>Status</th>
						<th class="text-center">Actions</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var medicine in Model)
					{
						<partial name="_Medicine" model="medicine" />
					}
				</tbody>
			</table>
		</div>
	</div>
	<!--End Card::Body-->
</div>
<div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-header">
				<h1 class="modal-title fs-5" id="ModalLabel"></h1>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<!--Generated By Javascript-->
			</div>
		</div>
	</div>
</div>
<input type="hidden" name="__RequestVerificationToken" value="@antiforgery.GetAndStoreTokens(Context).RequestToken" id="tokkenForgery" />

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
	<script src="~/assets/Plugins/datatables/datatables.bundle.js"></script>
}

DentistClinic/Views/Medicines/_Form.cshtml
@model MedicineViewModel;

<form id="MedicinesForm" asp-controller="Medicines" asp-action=@(Model.Id == null ? "Create" : "Update")
      data-ajax-method="post"
      data-ajax="true"
      data-ajax-begin="onRequestBegin"
      data-ajax-success="onRequestSuccess"
      data-ajax-failure="onRequestFailure"
      data-ajax-complete="onRequestComplete">
    <div class="row">
        <div class="col-12">
            <div class="mb-3">
                <div class="form-floating mb-2">
                    <input class="form-control form-control-solid" asp-for="Name" placeholder="Name..." />
                    <label class="form-label" asp-for="Name"></label>
                </div>
                <span class="text-danger d-block" asp-validation-for="Name"></span>
            </div>
        </div>
        <div class="col-12">
            <div class="mb-3">
                <div class="form-floating mb-2">
                    <select class="form-select form-select-solid js-select2" asp-for="Type" data-placeholder="Select an Type">
                        <option value="">Select Medicine Type</option>
                        <option value="Syrap">Syrap</option>
                        <option value="Vial">Vial</option>
                        <option value="Tablet">Tablet</option>
                        <option value="Capsules">Capsules</option>
                        <option value="Sachets">Sachets</option>
                        <option value="Drops">Drops</option>
                        <option value="Inhalers">Inhalers</option>
                        <option value="Topical">Topical</option>
                        <option value="(Injection) Ampoule IV">(Injection) Ampoule IV"</option>
                        <option value="(Injection) Ampoule IM">(Injection) Ampoule IM"</option>
                        <option value="(Injection) Ampoule SC">(Injection) Ampoule SC"</option>
                        <option value="Sublingual Tablets">Sublingual Tablets</option>
                        <option value="Patches">Patches</option>
                    </select>
                    <label class="form-label" asp-for="Type"></label>
                </div>
                <span class="text-danger d-block" asp-validation-for="Type"></span>
            </div>
        </div>
        <div class="col-12 mt-5">
            <div class="actions">
                <button type="button" class="btn-sm btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn-sm btn btn-@(Model.Id == null ? "primary" : "warning")  me-2">
                    <span class="indicator-label">
                        @(Model.Id == null ? "Add" : "Edit")
                    </span>
                    <span class="indicator-progress">
                        Please wait... <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                    </span>
                </button>
            </div>
        </div>
    </div>
</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

DentistClinic/Views/Medicines/_Medicine.cshtml
@model MedicineViewModel;
<tr>
	<td>@Model.Name</td>
	<td>@Model.Type</td>
	@if (!Model.IsDeleted)
	{
		<td>
			<span class=" js-status badge badge-light-success me-auto">
				Available
			</span>
		</td>
	}
	else
	{
		<td>
			<span class=" js-status badge badge-light-danger me-auto">
				Deleted
			</span>
		</td>
	}
	<td class="text-center">
		<a href="#" class="btn btn-light btn-active-light-primary btn-flex btn-center btn-sm" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
			Actions
			<span class="svg-icon svg-icon-muted svg-icon-5">
				<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
					<path d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z" fill="currentColor" />
				</svg>
			</span>
		</a>
		<div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 w-125px py-4" data-kt-menu="true" style="">
			<div class="menu-item px-3">
				<a class="menu-link px-3 js-render-modal" data-update="true" data-url="/Medicines/Update/@Model.Id" data-title="Edit Medicines">
					Edit
				</a>
			</div>
			<div class="menu-item px-3">
				<a class="menu-link px-3 js-toggle-status" data-url="/Medicines/ToggleStatus/@Model.Id">
					Toggle Status
				</a>
			</div>
		</div>
	</td>
</tr>