DentistClinic/Controllers/XrayController.cs
using DentistClinic.Core.Models;
using DentistClinic.Core.ViewModels;
using DentistClinic.CustomeValidation;
using DentistClinic.Services.Interfaces;
using DentistClinic.Services.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace DentistClinic.Controllers
{
    [Authorize(Roles = "Doctor")]
    public class XrayController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public XrayController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<XraysViewModel> vmodel = _unitOfWork.xrayRepository.GetAll().Select(x => new XraysViewModel
            {
                Id = x.Id,
                Name = x.Name,
                Type = x.Type,
                IsDeleted = x.IsDeleted
            }).ToList();

			return View(vmodel);
        }

		[AjaxOnly]
		[HttpGet]
		public IActionResult Create()
		{
			XraysViewModel viewModal = new XraysViewModel();

			return PartialView("_Form", viewModal);
		}

        [AjaxOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(XraysViewModel model)
        {

            if (ModelState.IsValid)
            {
                Xray xray = new Xray();

                xray.Name = model.Name;
                xray.Type = model.Type;

                _unitOfWork.xrayRepository.Create(xray);

				model.Id = xray.Id;
                return PartialView("_Xray" , model);
            }
            else
            {
                return BadRequest("something is wrong..!!");
            }

        }


		[AjaxOnly]
		[HttpGet]
		public IActionResult Update(int id)
		{
            Xray xray = _unitOfWork.xrayRepository.GetById(id);

            if(xray != null)
            {
				XraysViewModel viewModal = new XraysViewModel
				{
					Id = xray.Id,
					Name = xray.Name,
					Type = xray.Type,
					IsDeleted = xray.IsDeleted,
				};

				return PartialView("_Form", viewModal);
			}
            else
            {
				return BadRequest("something is wrong..!!");
			}

			
		}

		[AjaxOnly]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Update(XraysViewModel model)
		{
			if (ModelState.IsValid)
			{
				Xray xray = _unitOfWork.xrayRepository.GetById((int)model.Id!);

				if (xray != null)
				{

					xray.Name = model.Name;
					xray.Type = model.Type;

					_unitOfWork.xrayRepository.Update(xray);
                    model.IsDeleted = xray.IsDeleted;
					return PartialView("_Xray", model);
				}
				else
				{
					return BadRequest("something is wrong..!!");
				}
				
			}
			else
			{
				return BadRequest("something is wrong..!!");
			}
			
			

		}
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AjaxOnly]
        public IActionResult ToggleStatus(int id)
        {
            Xray xray = _unitOfWork.xrayRepository.GetById(id);

            if (xray != null)
            {
                xray.IsDeleted = !xray.IsDeleted;
                _unitOfWork.xrayRepository.Update(xray);

                XraysViewModel viewModel = new XraysViewModel();
                viewModel.Name = xray.Name;
                viewModel.Type = xray.Type;
                viewModel.IsDeleted = xray.IsDeleted;

                return Ok(viewModel);
            }
            else
            {
                return NotFound();
            }
        }
    }
}

DentistClinic/Views/Xray/Index.cshtml
@model IEnumerable<XraysViewModel>
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery antiforgery;

@{
    ViewData["Title"] = "Index";
}

@section Styles {
	<link rel="stylesheet" href="~/assets/Plugins/datatables/datatables.bundle.css" />
}

<div class="bg-light-primary border border-primary border-3 border-dashed d-flex justify-content-between rounded w-100 p-5 mb-10">
	<div class="d-flex align-items-center">
		<div class="symbol symbol-40px me-4">
			<div class="symbol-label fs-2 fw-semibold">
				<!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
				<span class="svg-icon svg-icon-2 svg-icon-primary">
					<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" fill="none">
						<path d="M0 64C0 46.3 14.3 32 32 32H480c17.7 0 32 14.3 32 32s-14.3 32-32 32V416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32V96C14.3 96 0 81.7 0 64zM256 96c-8.8 0-16 7.2-16 16v32H160c-8.8 0-16 7.2-16 16s7.2 16 16 16h80v48H128c-8.8 0-16 7.2-16 16s7.2 16 16 16H240v70.6L189.1 307c-5.2-2-10.6-3-16.2-3h-2.1c-23.6 0-42.8 19.2-42.8 42.8c0 9.6 3.2 18.9 9.1 26.4l18.2 23.2c9.7 12.4 24.6 19.6 40.3 19.6H316.4c15.7 0 30.6-7.2 40.3-19.6l18.2-23.2c5.9-7.5 9.1-16.8 9.1-26.4c0-23.6-19.2-42.8-42.8-42.8H339c-5.5 0-11 1-16.2 3L272 326.6V256H384c8.8 0 16-7.2 16-16s-7.2-16-16-16H272V176h80c8.8 0 16-7.2 16-16s-7.2-16-16-16H272V112c0-8.8-7.2-16-16-16zM208 352a16 16 0 1 1 0 32 16 16 0 1 1 0-32zm80 16a16 16 0 1 1 32 0 16 16 0 1 1 -32 0z" fill="currentColor" />
					</svg>
				</span>
				<!--end::Svg Icon-->
			</div>
		</div>
		<!--begin::Content-->
		<div class="d-flex flex-column pe-0 pe-sm-10">
			<h5 class="mb-1">Xrays</h5>
		</div>
		<!--end::Content-->
	</div>
	<div>
		<a class="btn btn-sm btn-primary js-render-modal" href="javascript:;" data-url="/Xray/Create" data-title="Add New X-Ray">
			<i class="bi bi-plus-square-dotted"></i>
			Add
		</a>
	</div>
</div>
<div class="card shadow-sm">
	<!--Begin Card::Header-->
	<div class="card-header">
		<partial name="_DatatableCardHeader" />
		<div class="card-toolbar flex-row-fluid justify-content-end gap-5">
			<!--begin::Export dropdown-->
			<button type="button" class="btn btn-light-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
				<i class="ki-duotone ki-exit-down fs-2"><span class="path1"></span><span class="path2"></span></i>
				Export Report
			</button>
			<!--begin::Menu-->
			<div id="kt_datatable_example_export_menu" class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 w-200px py-4" data-kt-menu="true">
				<!--begin::Menu item-->
				<div class="menu-item px-3">
					<a href="#" class="menu-link px-3" data-kt-export="copy">
						Copy to clipboard
					</a>
				</div>
				<!--end::Menu item-->
				<!--begin::Menu item-->
				<div class="menu-item px-3">
					<a href="#" class="menu-link px-3" data-kt-export="excel">
						Export as Excel
					</a>
				</div>
				<!--end::Menu item-->
				<!--begin::Menu item-->
				<div class="menu-item px-3">
					<a href="#" class="menu-link px-3" data-kt-export="csv">
						Export as CSV
					</a>
				</div>
				<!--end::Menu item-->
				<!--begin::Menu item-->
				<div class="menu-item px-3">
					<a href="#" class="menu-link px-3" data-kt-export="pdf">
						Export as PDF
					</a>
				</div>
				<!--end::Menu item-->
			</div>
			<!--end::Menu-->
			<!--end::Export dropdown-->
			<!--begin::Hide default export buttons-->
			<div id="kt_datatable_example_buttons" class="d-none"></div>
		</div>
	</div>
	<!--End Card::Header-->
	<div class="card-body pt-0">
		<div class="table-responsive">
			<table id="kt_datatable_zero_configuration" class="js-datatables table table-row-dashed table-row-gray-300 gy-3 align-middle">
				<thead>
					<tr class="fw-bold fs-6 text-gray-800">
						<th>Name</th>
						<th>Type</th>
						<th>Status</th>
						<th class="text-center px-5">Actions</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var xray in Model)
					{
						<partial name="_Xray" model="xray" />
					}
				</tbody>
			</table>
		</div>
	</div>
	<!--End Card::Body-->
</div>
<div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-header">
				<h1 class="modal-title fs-5" id="ModalLabel"></h1>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<!--Generated By Javascript-->
			</div>
		</div>
	</div>
</div>
<input type="hidden" name="__RequestVerificationToken" value="@antiforgery.GetAndStoreTokens(Context).RequestToken" id="tokkenForgery" />

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
	<script src="~/assets/Plugins/datatables/datatables.bundle.js"></script>
}

DentistClinic/Views/Xray/_Form.cshtml
@model XraysViewModel;

<form id="XrayForm" asp-controller="Xray" asp-action=@(Model.Id == null ? "Create" : "Update")
      data-ajax-method="post"
      data-ajax="true"
      data-ajax-begin="onRequestBegin"
      data-ajax-success="onRequestSuccess"
      data-ajax-failure="onRequestFailure"
      data-ajax-complete="onRequestComplete">
    <div class="row">
        <div class="col-12">
            <div class="mb-3">
                <div class="form-floating mb-2">
                    <input class="form-control form-control-solid" asp-for="Name" placeholder="Name..." />
                    <label class="form-label" asp-for="Name"></label>
                </div>
                <span class="text-danger d-block" asp-validation-for="Name"></span>
            </div>
        </div>
        <div class="col-12">
            <div class="mb-3">
                <div class="form-floating mb-2">
                    <select class="form-select form-select-solid js-select2" asp-for="Type" data-placeholder="Select an Type">
                        <option value="">Selet X-Ray Type</option>
                        <option value="Panorama">Panorama</option>
                        <option value="CBCT">CBCT</option>
                        <option value="Periapical">Periapical</option>
                        <option value="MRI">MRI</option>
                    </select>
                    <label class="form-label" asp-for="Type"></label>
                </div>
                <span class="text-danger d-block" asp-validation-for="Type"></span>
            </div>
        </div>
        <div class="col-12 mt-5">
            <div class="actions">
                <button type="button" class="btn-sm btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn-sm btn btn-@(Model.Id == null ? "primary" : "warning")  me-2">
                    <span class="indicator-label">
                        @(Model.Id == null ? "Add" : "Edit")
                    </span>
                    <span class="indicator-progress">
                        Please wait... <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                    </span>
                </button>
            </div>
        </div>
    </div>
</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

DentistClinic/Views/Xray/_Xray.cshtml
@model XraysViewModel;

<tr>
	<td>@Model.Name</td>
	<td>@Model.Type</td>
	@if (!Model.IsDeleted)
	{
		<td>
			<span class=" js-status badge badge-light-success me-auto">
				Available
			</span>
		</td>
	}
	else
	{
		<td>
			<span class=" js-status badge badge-light-danger me-auto">
				Deleted
			</span>
		</td>
	}
	<td class="text-center">
		<a href="#" class="btn btn-light btn-active-light-primary btn-flex btn-center btn-sm" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
			Actions
			<span class="svg-icon svg-icon-muted svg-icon-5">
				<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
					<path d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z" fill="currentColor" />
				</svg>
			</span>
		</a>
		<div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 w-125px py-4" data-kt-menu="true" style="">
			<div class="menu-item px-3">
				<a  class="menu-link px-3 js-render-modal" data-update="true" data-url="/Xray/Update/@Model.Id" data-title="Edit Xray">
					Edit
				</a>
			</div>
			<div class="menu-item px-3">
				<a class="menu-link px-3 js-toggle-status" data-url="/Xray/ToggleStatus/@Model.Id">
					Toggle Status
				</a>
			</div>
		</div>
	</td>
</tr>